hcplayers/urls.py
from django.urls import path, include
from .import views

app_name = 'plr'

urlpatterns = [
    path('', views.post_list, name='player_list'),
    path('<slug:player>', views.PlayerDetailView.as_view(), name='player_detail'),
    path('search/', views.player_search, name='player_search'),
    path('hitcount/', include(('hitcount.urls', 'hitcount'), namespace='hitcount'))
]

hockey_plrs/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('hcplayers.urls', namespace='plr'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hcplayers/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.utils.text import slugify
from django.contrib.contenttypes.fields import GenericRelation

from hitcount.models import HitCountMixin, HitCount


class Player(models.Model, HitCountMixin):
    first_name = models.CharField(max_length=100, default='Имя')
    last_name = models.CharField(max_length=100, default='Фамилия')
    date_of_birth = models.DateField()
    description = models.TextField(blank=True)
    slug = models.SlugField(unique=True, max_length=200)
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    player_photo = models.ImageField(upload_to='player_images/')
    hit_count_generic = GenericRelation(HitCount, object_id_field='object_pk',
        related_query_name='hit_count_generic_relation')

    def get_absolute_url(self):
        return reverse('plr:player_detail',
                       args=[self.slug])

    def __str__(self):
        return self.first_name + ' ' + self.last_name

    def save(self, *args, **kwargs):
        # img = Image.open(self.player_photo.path)
        # if img.height > 512 or img.width > 512:
        #     output_size = (512, 512)
        #     img.thumbnail(output_size)
        #     img.save(self.player_photo.path)
        if not self.slug:
            self.slug = slugify(self.first_name + ' ' + self.last_name)
        super().save(*args, **kwargs)


class Comment(models.Model):
    player = models.ForeignKey(Player, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80)
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

hcplayers/forms.py
from django import forms
from .models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'body')


class SearchForm(forms.Form):
    query = forms.CharField()

hcplayers/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from hitcount.views import HitCountDetailView
from django.contrib.postgres.search import SearchVector

from .models import Player
from .forms import CommentForm, SearchForm


def post_list(request):
    object_list = Player.objects.all()
    paginator = Paginator(object_list, 3)
    page = request.GET.get('page')
    try:
        players = paginator.page(page)
    except PageNotAnInteger:
        players = paginator.page(1)
    except EmptyPage:
        players = paginator.page(paginator.num_pages)

    return render(request,
                  'hcplayers/playrs/list.html',
                  {'page': page,
                   'players': players})


class PlayerDetailView(HitCountDetailView):
    model = Player
    context_object_name = 'player'
    count_hit = True
    template_name = 'hcplayers/playrs/detail.html'

    def get(self, request, *args, **kwargs):
        self.object = get_object_or_404(Player, slug=self.kwargs.get('player'))
        comments = self.object.comments.filter(active=True)
        context = self.get_context_data(object=self.object)
        new_comment = None
        comment_form = CommentForm
        context['comment_form'] = comment_form
        context['new_comment'] = new_comment
        context['comments'] = comments
        return self.render_to_response(context)

    def post(self, request, *args, **kwargs):
        comment_form = CommentForm(request.POST)
        new_comment = None
        if comment_form.is_valid():
            context = super().get_context_data(**kwargs)
            new_comment = comment_form.save(commit=False)
            new_comment.player = get_object_or_404(Player, slug=self.kwargs.get('player'))
            new_comment.save()
            context['comment_form'] = CommentForm
            context['new_comment'] = new_comment
            return self.render_to_response(context=context)
        else:
            context = super().get_context_data(**kwargs)
            context['comment_form'] = comment_form
            return self.render_to_response(context=context)

def player_detail(request, player):
    player = get_object_or_404(Player,
                               slug=player)
    comments = player.comments.filter(active=True)
    new_comment = None
    if request.method == 'POST':
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.player = player
            new_comment.save()
    else:
        comment_form = CommentForm
    return render(request,
                  'hcplayers/playrs/detail.html',
                  {'player': player,
                   'comments': comments,
                   'new_comment': new_comment,
                   'comment_form': comment_form})


def player_search(request):
    form = SearchForm()
    query = None
    results = []
    if "query" in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            results = Player.objects.annotate(
                search=SearchVector('first_name', 'last_name')
            ).filter(search=query)

    return render(request,
                  'hcplayers/playrs/search.html',
                  {'form': form,
                   'query': query,
                   'results': results})

hcplayers/templates/hcplayers/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <div id="content">
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

hcplayers/templates/hcplayers/playrs/detail.html
{% extends 'hcplayers/base.html' %}
{% load hitcount_tags %}

{% block title %}{{ player.name }}{% endblock %}

{% block content %}
    <p>Views: {% get_hit_count for player %}</p>
    <h1>{{ player.last_name }} {{ player.first_name }}</h1>
    <img src="{{ player.player_photo.url }}">
    <p>Date of birth: {{ player.date_of_birth }}</p>
    <p>{{ player.description }}</p>
    <p><a href="{% url "plr:player_list" %}">Players list</a></p>
    {% with player.comments.count as total_comments %}
    <h2>
        {{ total_comments }} comment {{ total_comments|pluralize }}
    </h2>
    {% endwith %}
    {% for comment in comments %}
        <div class="comment">
            <p class="info">
                Comment {{ forloop.counter }} by {{ comment.name }}
                {{ comment.created }}
            </p>
        {{ comment.body|linebreaks }}
        </div>
        {% empty %}
            <p>Комментариев еще нет</p>
    {% endfor %}
    {% if new_comment %}
        <h2>Комментарий был добавлен</h2>
        <h2>Добавить комментарий</h2>
        <form method="post">
            {{ comment_form.as_p }}
            {% csrf_token %}
            <p><input type="submit" value="Добавить комментарий"></p>
        </form>
    {% else %}
        <h2>Добавить комментарий</h2>
        <form method="post">
            {{ comment_form.as_p }}
            {% csrf_token %}
            <p><input type="submit" value="Добавить комментарий"></p>
        </form>
    {% endif %}
{% endblock %}

hcplayers/templates/hcplayers/playrs/list.html
{% extends 'hcplayers/base.html' %}

{% block title %}Hockey players{% endblock %}

{% block content %}
    {% for player in players %}
        <h2>
            <a href="{{ player.get_absolute_url }}">{{ player.last_name }} {{ player.first_name }}</a>
        </h2>
    {% endfor %}
    {% include "pagination.html" with page=players %}
    <p><a href="{% url "plr:player_search" %}">Search</a></p>
{% endblock %}

hcplayers/templates/hcplayers/playrs/search.html
{% extends 'hcplayers/base.html' %}

{% block title %}Search{% endblock %}

{% block content %}
    {% if query %}
        <h1>Search results containing "{{ query }}"</h1>
        <h3>
            {% with results.count as total_results %}
                Найдено: {{ total_results }} result{{ total_results|pluralize }}
            {% endwith %}
        </h3>
        {% for player in results %}
            <h4><a href="{{ player.get_absolute_url }}">{{ player.first_name }} {{ player.last_name }}</a></h4>
            {% empty %}
                <p>No results.</p>
        {% endfor %}
        <p><a href="{% url "plr:player_search" %}">Search again</a></p>
    {% else %}
        <h1>Search players</h1>
        <form method="get">
            {{ form.as_p }}
            <input type="submit" value="Search">
        </form>
    {% endif %}
    <p><a href="{% url "plr:player_list" %}">Players list</a></p>
{% endblock %}

hcplayers/templates/pagination.html
<div>
    <span>
        {% if page.has_previous %}
            <a href="?page={{ page.previous_page_number }}">Prev</a>
        {% endif %}
    <span>
        Page {{ page.number }} of {{ page.paginator.num_pages }}
    </span>
    {% if page.has_next %}
        <a href="?page={{ page.next_page_number }}">Next</a>
    {% endif %}
    </span>
</div>